version: 2
updates:
#   - package-ecosystem: gomod
#     directory: "/"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     ignore:
#       # Breaks backwards compatibility
#       - dependency-name: github.com/gravitational/ttlmap
#       # Must be kept in-sync with libbpf
#       - dependency-name: github.com/aquasecurity/libbpfgo
#       # Forked/replaced dependencies
#       - dependency-name: github.com/alecthomas/kingpin/v2
#       - dependency-name: github.com/coreos/go-oidc
#       - dependency-name: github.com/go-mysql-org/go-mysql
#       - dependency-name: github.com/gogo/protobuf
#       - dependency-name: github.com/julienschmidt/httprouter
#       - dependency-name: github.com/keys-pub/go-libfido2
#       - dependency-name: github.com/microsoft/go-mssqldb
#       - dependency-name: github.com/redis/go-redis/v9
#       - dependency-name: github.com/vulcand/predicate
#     open-pull-requests-limit: 10
#     groups:
#       go:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - jentfoo
#       - rosstimothy
#       - zmb3
# 
#   - package-ecosystem: gomod
#     directory: "/api"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     open-pull-requests-limit: 10
#     groups:
#       go:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - jentfoo
#       - rosstimothy
#       - zmb3
# 
#   - package-ecosystem: gomod
#     directory: "/assets/aws"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     ignore:
#       # Forked/replaced dependencies
#       - dependency-name: github.com/alecthomas/kingpin/v2
#     open-pull-requests-limit: 10
#     groups:
#       go:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - jentfoo
#       - rosstimothy
#       - tcsc
#       - zmb3
# 
#   - package-ecosystem: gomod
#     directory: "/assets/backport"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     open-pull-requests-limit: 10
#     groups:
#       go:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - jentfoo
#       - rosstimothy
#       - zmb3
# 
#   - package-ecosystem: gomod
#     directory: "/build.assets/tooling"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     ignore:
#       # Forked/replaced dependencies
#       - dependency-name: github.com/alecthomas/kingpin/v2
#     open-pull-requests-limit: 10
#     groups:
#       go:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - fheinecke
#       - jentfoo
#       - rosstimothy
#       - zmb3
# 
#   - package-ecosystem: gomod
#     directory: "/integrations/kube-agent-updater"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     open-pull-requests-limit: 10
#     groups:
#       go:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - hugoShaka
#       - jentfoo
#       - rosstimothy
#       - zmb3
# 
#   - package-ecosystem: cargo
#     directory: "/"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     open-pull-requests-limit: 10
#     groups:
#       rust:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - ibeckermayer
#       - jentfoo
#       - rosstimothy
#       - zmb3
# 
#   - package-ecosystem: cargo
#     directory: "/lib/srv/desktop/rdp/rdpclient"
#     schedule:
#       interval: weekly
#       day: "sunday"
#       time: "09:00" # 9am UTC
#     open-pull-requests-limit: 10
#     groups:
#       rust:
#         update-types:
#           - "minor"
#           - "patch"
#     reviewers:
#       - codingllama
#       - ibeckermayer
#       - jentfoo
#       - rosstimothy
#       - zmb3
