# This workflow combines all open Dependabot PRs into a single batched
# PR, links all the Dependabot PRs to the new one, and closes all the
# Dependabot PRs. The schedule is set to exactly 12 hours after the
# Dependabot schedule.
#
# All workflows that run on PR should be skipped for Dependabot PRs
# to prevent wasting CI cycles.
name: 'Dependabot Batcher'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 0' # At 9:00 PM every Sunday UTC
          
jobs:
  dependabot-batcher:
    name: 'Combine Dependabot PRs'
    runs-on: ubuntu-latest
    environment: dependabot-batcher
    steps:
      - name: Generate GitHub Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
      - name: 'Dependabot Batcher'
        uses: Legal-and-General/dependabot-batcher@v1.0.3
        with:
          token: ${{ steps.generate_token.outputs.token }} #required
          baseBranchName: 'master'
