name: Update AMI IDs

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Release version tag (ex. 12.1.0)

  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Release version tag (ex. 12.1.0)

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  update-ami-ids:
    name: Update AMI IDs
    runs-on: ubuntu-latest
    environment: post-release

    steps:
      - name: Generate Github token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region:  us-west-2
          role-to-assume: "arn:aws:iam::126027368216:role/tf-teleport-ami-gha-role"
          role-session-name: "gha-update-ami-ids-${{ github.run_number }}"

      - name: Update AMI IDs and create PR
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub"
          TELEPORT_VERSION=${{ inputs.version }} make -C assets/aws create-update-pr
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
